package org.example.model;
public enum EventType {
	LOGIN_SUCCESS,
	LOGIN_FAILED,
	MESSAGE_SENT,
	MESSAGE_DELIVERED,
	USER_OFFLINE,
	MESSAGE_RECEIVED,
	ERROR,
	LOGOUT_SUCCESS,
	BROADCAST_RECEIVED,
	USER_CONNECTED,
	USER_DISCONNECTED,
	OFFLINE_MESSAGE_RECEIVED,
	HEARTBEAT_ACK
}
